// Date format is : MM:DD:YY

export const apiData = [
  {
    id: 1,
    title: "Things Fall Apart",
    startDate: new Date("4/1/2023"),
    endDate: new Date("4/1/2023"),
    startTime: "7:00",
    endTime: "8:45",
    clientImg:
      "/imgs/dog-golden-retriever-jumping-autumn-leaves-autumnal-sunlight-77861618.jpg",
    clientName: "Ajuri Alaka",
    appointmentWith: "Dr.Samie Ejor",
    appointmentWithId: "dc-1",
    appointmentWithImg: "/imgs/images (1).jpg",
  },
  {
    id: 2,
    title: "Half of a Yellow Sun",
    startDate: new Date("5/1/2023"),
    endDate: new Date("5/1/2023"),
    startTime: "9:00",
    endTime: "10:00",
    clientImg: "/imgs/images.jpg",
    clientName: "Janet Dope",
    appointmentWith: "Dr.Justin Land",
    appointmentWithId: "dc-2",
    appointmentWithImg: "/imgs/istockphoto-1067347086-612x612.jpg",
  },
  {
    id: 3,
    title: "Purple Hibiscus",
    startDate: new Date("4/6/2023"),
    endDate: new Date("4/6/2023"),
    startTime: "8:00",
    endTime: "9:00",
    clientImg: "/imgs/istockphoto-1191962502-612x612.jpg",
    clientName: "Jon Doe",
    appointmentWith: "Dr.Janet Jolls",
    appointmentWithId: "dc-3",
    appointmentWithImg:
      "/imgs/two-cute-golden-retriever-puppies-playing-photo-45116795.jpg",
  },
  {
    id: 4,
    title: "There was a country",
    startDate: new Date("4/3/2023"),
    endDate: new Date("4/3/2023"),
    startTime: "9:00",
    endTime: "10:30",
    clientImg: "/imgs/istockphoto-1191962502-612x612.jpg",
    clientName: "Asa Nwa",
    appointmentWith: "Dr.Samie Ejor",
    appointmentWithId: "dc-1",
    appointmentWithImg: "/imgs/images (1).jpg",
  },
];
